### ISSUE TITLE
Error on build with gcc-go

### ISSUE THREAD

**Issue by brockers** [senorprogrammer/wtf#180]
#### Summary

Running `make install` results in the following error.
```sh
go build -o bin/wtf
# github.com/senorprogrammer/wtf/gcal
gcal/widget.go:234:21: error: reference to undefined field or method ‘Round’
  duration = duration.Round(time.Minute)
                     ^
make: *** [Makefile:6: build] Error 2
```
The program correctly builds with golang 1.9.6

##### What is the current behaviour?
Does not build

### How to reproduce

* go get -u github.com/senorprogrammer/wtf
* cd $GOPATH/src/github.com/senorprogrammer/wtf
* make install

### System

Fedora 27 x86-64 gcc-go 7.3.1

**Comment by senorprogrammer** [comment]
"GCC 7 releases include a complete implementation of the Go 1.8.1 user libraries"

WTF uses core functionality added in Go 1.9. It is not compatible with earlier Go versions.
